version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto:${SOFTWARE_VERSION_TAG}
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "172.17.0.1:32691:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      # - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
